- id: '1672391329611'
  alias: Démarrer aspirateur par zone
  description: ''
  trigger: []
  condition: []
  action:
  - service: vacuum.stop
    target:
      entity_id: vacuum.victor
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: script.turn_on
    data:
      entity_id: "{% if is_states ('input_select.aspirateur_pieces','Bureau') %}\n
        \ script.s_aspirateur_bureau\n{% elif is_states ('input_select.aspirateur_pieces','Chambre')
        %}\n  script.s_aspirateur_chambre\n{% elif is_states ('input_select.aspirateur_pieces','Dressing')
        %}\n  script.s_aspirateur_dressing\n{% elif is_states ('input_select.aspirateur_pieces','Salle
        de bain') %}\n  script.s_aspirateur_salledebain\n{% elif states.input_select.aspirateur_pieces
        == \"Salon/Cuisine\" %}\n  script.s_aspirateur_salon_cuisine\n{% elif states.input_select.aspirateur_pieces
        == \"Toilette\" %}\n  script.s_aspirateur_toilette\n{% endif %}\n"
  mode: single
- id: '1674036635482'
  alias: test mouvement + condition lux
  description: si mouvement et moins de 50 lux => notif super21
  trigger:
  - type: motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - type: is_illuminance
    condition: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
    domain: sensor
    below: 50
  action:
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    message: ça marche !
    title: test mouvement + lux
  mode: single
