- id: '1672391329611'
  alias: Appartement_aspirateur_zone
  description: ''
  trigger: []
  condition: []
  action:
  - service: vacuum.stop
    target:
      entity_id: vacuum.victor
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: script.turn_on
    data:
      entity_id: "{% if is_states ('input_select.aspirateur_pieces','Bureau') %}\n
        \ script.s_aspirateur_bureau\n{% elif is_states ('input_select.aspirateur_pieces','Chambre')
        %}\n  script.s_aspirateur_chambre\n{% elif is_states ('input_select.aspirateur_pieces','Dressing')
        %}\n  script.s_aspirateur_dressing\n{% elif is_states ('input_select.aspirateur_pieces','Salle
        de bain') %}\n  script.s_aspirateur_salledebain\n{% elif states.input_select.aspirateur_pieces
        == \"Salon/Cuisine\" %}\n  script.s_aspirateur_salon_cuisine\n{% elif states.input_select.aspirateur_pieces
        == \"Toilette\" %}\n  script.s_aspirateur_toilette\n{% endif %}\n"
  mode: single
- id: '1674036635482'
  alias: Salon_mouvement-lux_light_ON
  description: si mouvement + lux => allume salon
  trigger:
  - type: motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - type: is_illuminance
    condition: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
    domain: sensor
    below: 60
  - condition: device
    type: is_off
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  - condition: device
    type: is_off
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
  action:
  - type: turn_on
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
    brightness_pct: 100
  mode: single
- id: '1674056461573'
  alias: Salon_NoMouvement-2min_lights_OFF
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: device
    device_id: ab5eb56734a3754889bd3a0f23ff6f07
    domain: media_player
    entity_id: media_player.lg_webos_tv_214e
    type: is_idle
  action:
  - type: turn_off
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  - type: turn_off
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
  mode: single
- id: '1674057301650'
  alias: Salon_lux_light_Off
  description: ''
  trigger:
  - type: illuminance
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
    domain: sensor
    above: 60
  condition: []
  action:
  - type: turn_off
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  - type: turn_off
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
  mode: single
- id: '1674058676939'
  alias: Salon_TV-lux_Amibilight_ON
  description: ''
  trigger:
  - platform: device
    device_id: ab5eb56734a3754889bd3a0f23ff6f07
    domain: media_player
    entity_id: media_player.lg_webos_tv_214e
    type: turned_on
  condition:
  - type: is_illuminance
    condition: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
    domain: sensor
    below: 60
  action:
  - type: turn_off
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  - type: turn_on
    device_id: dbfcac9e2516dd6484ff2261d038bcd2
    entity_id: light.hyperhdr
    domain: light
    brightness_pct: 100
  mode: single
- id: '1674070315654'
  alias: Salon_Nfc_light-entrée_ON/OFF
  description: ''
  trigger:
  - platform: tag
    tag_id: 8dabc0dc-0b59-4a51-abaa-23c2453b3781
  condition: []
  action:
  - type: toggle
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  mode: single
- id: '1674119803862'
  alias: Salon_TV-lux_Ambilight_OFF
  description: ''
  trigger:
  - platform: device
    device_id: 1ef132b28f63368f6b81c3e09867065a
    domain: media_player
    entity_id: media_player.tele
    type: turned_on
  condition:
  - type: is_illuminance
    condition: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
    domain: sensor
    above: 60
  action:
  - type: turn_off
    device_id: dbfcac9e2516dd6484ff2261d038bcd2
    entity_id: light.hyperhdr
    domain: light
  mode: single
- id: '1674120488553'
  alias: Salon_nuit_SensibilitéMouvement_Low
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: time
    after: 00:00:00
    before: 06:00:00
    weekday: []
  action:
  - device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    domain: select
    entity_id: select.0x54ef4410005a8dc9_motion_sensitivity
    type: select_option
    option: low
  mode: single
