- id: '1672391329611'
  alias: Appartement_aspirateur_zone
  description: ''
  trigger: []
  condition: []
  action:
  - service: vacuum.stop
    target:
      entity_id: vacuum.victor
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: script.turn_on
    data:
      entity_id: "{% if is_states ('input_select.aspirateur_pieces','Bureau') %}\n
        \ script.s_aspirateur_bureau\n{% elif is_states ('input_select.aspirateur_pieces','Chambre')
        %}\n  script.s_aspirateur_chambre\n{% elif is_states ('input_select.aspirateur_pieces','Dressing')
        %}\n  script.s_aspirateur_dressing\n{% elif is_states ('input_select.aspirateur_pieces','Salle
        de bain') %}\n  script.s_aspirateur_salledebain\n{% elif states.input_select.aspirateur_pieces
        == \"Salon/Cuisine\" %}\n  script.s_aspirateur_salon_cuisine\n{% elif states.input_select.aspirateur_pieces
        == \"Toilette\" %}\n  script.s_aspirateur_toilette\n{% endif %}\n"
  mode: single
- id: '1674036635482'
  alias: Salon_moi-mouvement-lux_light_ON
  description: si mouvement + lux => allume salon
  trigger:
  - type: motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: and
    conditions:
    - condition: device
      device_id: 2b61395c28cf69b6694f9a88c35a9df6
      domain: device_tracker
      entity_id: device_tracker.super21
      type: is_home
      enabled: true
    - type: is_illuminance
      condition: device
      device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
      entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
      domain: sensor
      below: 65
    - condition: device
      type: is_off
      device_id: dbfcac9e2516dd6484ff2261d038bcd2
      entity_id: light.hyperhdr_priority
      domain: light
  action:
  - type: turn_on
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
    brightness_pct: 100
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    message: Lumières ON. Du mouvement
    title: Automatisation
    enabled: false
  mode: single
- id: '1674056461573'
  alias: Salon_NoMouvement-3min_lights_OFF
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition:
  - condition: device
    type: is_off
    device_id: dbfcac9e2516dd6484ff2261d038bcd2
    entity_id: switch.hyperhdr_component_led_device
    domain: switch
  action:
  - type: turn_off
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  - type: turn_off
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    message: Plus de mouvements. Lumières Off
    title: Automatisations
    enabled: false
  mode: single
- id: '1674057301650'
  alias: Salon_lux_light_Off
  description: ''
  trigger:
  - type: illuminance
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
    domain: sensor
    above: 70
  condition:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: 687dad33e6d70811a28a821055adccd4
      entity_id: light.yeelight_color_entree
      domain: light
    - condition: device
      type: is_on
      device_id: 56937e4fc50a2019406b0874255917cd
      entity_id: light.yeelight_color_lampadaire
      domain: light
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_on
        device_id: 687dad33e6d70811a28a821055adccd4
        entity_id: light.yeelight_color_entree
        domain: light
      sequence:
      - type: turn_off
        device_id: 687dad33e6d70811a28a821055adccd4
        entity_id: light.yeelight_color_entree
        domain: light
    - conditions:
      - condition: device
        type: is_on
        device_id: 56937e4fc50a2019406b0874255917cd
        entity_id: light.yeelight_color_lampadaire
        domain: light
      sequence:
      - type: turn_off
        device_id: 56937e4fc50a2019406b0874255917cd
        entity_id: light.yeelight_color_lampadaire
        domain: light
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    title: Automatisation
    message: Lumières salon Off. Assez lumineux
  mode: single
- id: '1674119803862'
  alias: Salon_TV-lux_Ambilight_OFF
  description: ''
  trigger:
  - platform: device
    device_id: 1ef132b28f63368f6b81c3e09867065a
    domain: media_player
    entity_id: media_player.tele
    type: turned_on
  condition:
  - type: is_illuminance
    condition: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
    domain: sensor
    above: 70
    enabled: true
  action:
  - type: turn_off
    device_id: dbfcac9e2516dd6484ff2261d038bcd2
    entity_id: light.hyperhdr
    domain: light
  mode: single
- id: '1674132477823'
  alias: Github_Push configuration
  description: ''
  trigger: []
  action:
  - service: shell_command.pushconfiguration_github
    data: {}
- id: '1674471967437'
  alias: NFC cuisine
  description: ''
  trigger:
  - platform: tag
    tag_id: a7ad5671-2dc8-45d8-9707-226761c71bf1
  condition: []
  action:
  - type: toggle
    device_id: 17e652354e48f1c79fc876cec389ecf3
    entity_id: light.cuisine_1
    domain: light
  - type: toggle
    device_id: 92b6b011eea2ca2d6b0e1f032cb6b897
    entity_id: light.cuisine_2
    domain: light
  mode: single
- id: '1674478584185'
  alias: NFC entrée
  description: ''
  trigger:
  - platform: tag
    tag_id: 8dabc0dc-0b59-4a51-abaa-23c2453b3781
  condition: []
  action:
  - type: toggle
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  mode: single
- id: '1674478617865'
  alias: NFC entrée lampadaire
  description: ''
  trigger:
  - platform: tag
    tag_id: ca1a3ca8-e134-467f-a133-453d5cedf80b
  condition: []
  action:
  - type: toggle
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  - type: toggle
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
  mode: single
- id: '1674491056262'
  alias: Salon_TvPause_entree_ON
  description: ''
  trigger:
  - platform: device
    device_id: cccadbb1f56557877997f87d8d3b291c
    domain: media_player
    entity_id: media_player.android_tv_192_168_1_115
    type: paused
  condition:
  - condition: device
    type: is_on
    device_id: 56937e4fc50a2019406b0874255917cd
    entity_id: light.yeelight_color_lampadaire
    domain: light
  action:
  - type: turn_on
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
  mode: single
- id: '1674649451948'
  alias: Salon_matin_premier
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
    enabled: false
  - platform: state
    entity_id:
    - sensor.super21_next_alarm
  condition:
  - condition: and
    conditions:
    - condition: time
      after: 06:00:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - sat
      - fri
      - sun
      before: '10:00:00'
    - type: is_illuminance
      condition: device
      device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
      entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
      domain: sensor
      below: 60
      enabled: true
    - condition: numeric_state
      entity_id: counter.detection_mouvement
      below: 1
      enabled: false
    - type: is_not_plugged_in
      condition: device
      device_id: 2b61395c28cf69b6694f9a88c35a9df6
      entity_id: binary_sensor.super21_is_charging
      domain: binary_sensor
    - condition: zone
      entity_id: device_tracker.super21
      zone: zone.home
    enabled: true
  action:
  - service: script.compteur_mouvement
    data: {}
    enabled: true
  - type: turn_on
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
    enabled: true
    brightness_pct: 10
    flash: long
  mode: single
- id: '1674746964767'
  alias: Reset compteur mouvement
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: counter.reset
    data: {}
    target:
      entity_id: counter.detection_mouvement
  mode: single
- id: '1674863068011'
  alias: Compteur Aqara
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
  condition: []
  action:
  - service: script.compteur_mouvement
    data: {}
    enabled: false
  - service: counter.increment
    data: {}
    enabled: true
    target:
      entity_id: counter.detection_mouvement
  mode: single
- id: '1677834702352'
  alias: Rentre à la maison
  description: ''
  trigger:
  - platform: device
    device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: device_tracker
    entity_id: device_tracker.super21
    type: enters
    zone: zone.home
  condition:
  - condition: and
    conditions:
    - type: is_motion
      condition: device
      device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
      entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
      domain: binary_sensor
    - condition: device
      device_id: 84fe21f5b69ce4084ad41680653fb36c
      domain: media_player
      entity_id: 78c6213d6cb12c241f6e7bab78850646
      type: is_off
    - type: is_illuminance
      condition: device
      device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
      entity_id: sensor.0x54ef4410005a8dc9_illuminance_lux
      domain: sensor
      below: 65
  action:
  - type: turn_on
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: light.yeelight_color_entree
    domain: light
    brightness_pct: 100
  mode: single
- id: '1678007744793'
  alias: Détection chat
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: binary_sensor.0x54ef4410005a8dc9_occupancy
    domain: binary_sensor
  condition:
  - condition: device
    device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: device_tracker
    entity_id: device_tracker.super21
    type: is_not_home
  action:
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    title: Présence
    message: 'Détection d''un individu (chat) '
  mode: single
- id: '1678093524321'
  alias: Batterie thermostat
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: ff2f0e3339cc5e99b00b9492cd26e0f5
    entity_id: sensor.thermostat_battery_percent
    domain: sensor
    below: 50
  condition: []
  action:
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    message: Batterie thermostat inf à 50%
    title: Batterie alerte
  mode: single
- id: '1686345345804'
  alias: Update Map Extractor camera
  description: ''
  use_blueprint:
    path: PiotrMachowski/update_map_extractor.yaml
    input:
      vacuum: vacuum.victor
      camera: camera.victor
      mode_to_handle: two_intervals
      update_once_after_docking: false
      interval_cleaning: 300
      interval_docked: 10000
- id: '1686472336216'
  alias: Notification - Aspirateur en cours
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.roborock_vacuum_a08_last_clean_start
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition: []
  action:
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    message: Nettoyage en cours
    title: Aspirateur Victor
  mode: single
- id: '1687869622868'
  alias: 'Zone Susana '
  description: 'Hors Triboulet '
  trigger:
  - platform: zone
    entity_id: person.susana
    zone: zone.triboulet
    event: enter
  condition: []
  action:
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    title: Zone Susana
    message: 'Susana n''est plus à Triboulet '
  mode: single
- id: '1688968286371'
  alias: Entrée appartement
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: 0c78b683591cc333c864ed0091881b23
    domain: binary_sensor
    alias: 'Mouvement entrée détecté '
  condition:
  - type: is_illuminance
    condition: device
    device_id: 6d37dbde4b1751a27b3e7b8c1791fdc9
    entity_id: a84e34fa2fb56e6c4ecd3ae1f3d99ca8
    domain: sensor
    below: 65
    alias: Luminosité basse
  - condition: and
    conditions:
    - condition: device
      type: is_off
      device_id: 687dad33e6d70811a28a821055adccd4
      entity_id: 5ef39c9d6d725a3e4c9729af5b0e083e
      domain: light
    - condition: device
      type: is_off
      device_id: 56937e4fc50a2019406b0874255917cd
      entity_id: a0fea540b0b26aa81c0415f441cd6b34
      domain: light
  - condition: state
    entity_id: device_tracker.nmap_tracker_d2_a0_73_ba_c7_3d
    attribute: reason
    state: arp-response
  action:
  - type: turn_on
    device_id: 687dad33e6d70811a28a821055adccd4
    entity_id: 5ef39c9d6d725a3e4c9729af5b0e083e
    domain: light
  mode: single
- id: '1694499595267'
  alias: Alerte pluie
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.lyon_rain_chance
    from: '50'
  condition:
  - condition: time
    weekday:
    - tue
    - wed
  action:
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    message: Pluie
    title: Prends le parapluie
  mode: single
- id: '1697124381455'
  alias: Susana Annonay
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.iphone_marvel
    zone: zone.annonay
    event: leave
  condition: []
  action:
  - device_id: 2b61395c28cf69b6694f9a88c35a9df6
    domain: mobile_app
    type: notify
    message: 'Quitte Annonay '
    title: Susana
  mode: single
- id: '1699783167997'
  alias: Ios_Cuisine
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Light_cuisine
  condition: []
  action:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.interrupteur_cuisine
  mode: single
- id: '1699783827693'
  alias: Interrupteur cuisine
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.toggle_cuisine
    alias: Quand interrupteur cuisine
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.g_cuisine
  mode: single
- id: '1699784746258'
  alias: Interrupteur entrée
  description: ''
  trigger:
  - alias: Quand interrupteur entrée
    platform: state
    entity_id:
    - input_button.toggle_entree
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.yeelight_color_entree
  mode: single
- id: '1699784822278'
  alias: IOS_entrée
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Light_entree
  condition: []
  action:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.interrupteur_entree
  mode: single
- id: '1699784910050'
  alias: Interrupteur lampadaire
  description: ''
  trigger:
  - alias: Quand interrupteur lampadaire
    platform: state
    entity_id:
    - input_button.toggle_lampadaire
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.yeelight_color_lampadaire
  mode: single
- id: '1699785081385'
  alias: Ios_lampadaire
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Light_lampadaire
  condition: []
  action:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.interrupteur_lampadaire
  mode: single
